#!/bin/bash
if [ $# -ne 2 ]
then 
  echo "This file is used for encrypting hubot server file"
  echo "usage: encryptEnv [nonencryptedFilePath] [outputEcryptedFilePath]"
  exit
fi
if [ -f "$1" ]
  then
    echo "Encrypting $1 and storing it in $2"
    gpg -o $2 -r "Mr Devops" --batch --yes -e $1
    if [ $? == 0 ]
      then
        echo "encryption successful"
    else
      echo "encryption failed"
    fi
else
  echo "file $1"
fi